-- ============================================
-- 1. CREAR BASE DE DATOS
-- ============================================
CREATE DATABASE IF NOT EXISTS UrbanLife;
USE UrbanLife;

-- ============================================
-- 2. TABLAS INDEPENDIENTES
-- ============================================

CREATE TABLE Usuarios (
    ID_USUARIO INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE_USUARIO VARCHAR(100) NOT NULL,
    APELLIDO_USUARIO VARCHAR(100) NOT NULL,
    GOOGLE_ID VARCHAR(255) NULL UNIQUE,
    CONTRASENA VARCHAR(255) NULL,
    ESTADO_USUARIO BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE Roles (
    ID_ROLES INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE_ROL VARCHAR(100) NOT NULL,
    DESCRIPCION_ROL VARCHAR(255) NOT NULL
);

CREATE TABLE Permisos (
    ID_PERMISOS INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE_PERMISO VARCHAR(100) NOT NULL,
    DESCRIPCION_PERMISO VARCHAR(255) NOT NULL
);

CREATE TABLE Categorias (
    ID_CATEGORIA INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE_CATEGORIA VARCHAR(100) NOT NULL,
    DESCRIPCION_CATEGORIA VARCHAR(255),
    ESTADO_CATEGORIA BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE Tipos_Movimientos (
    ID_TIPO_MOVIMIENTOS INT AUTO_INCREMENT PRIMARY KEY,
    MOVIMIENTO ENUM('Venta', 'Compra', 'Gasto Adicional') NOT NULL,
    NATURALEZA ENUM('Ingreso', 'Egreso') NOT NULL
);

CREATE TABLE Clientes (
    ID_CLIENTE INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE_CLIENTE VARCHAR(150) NOT NULL,
    DOCUMENTO_CLIENTE BIGINT NULL UNIQUE,
    CORREO_CLIENTE VARCHAR(120) NULL UNIQUE,
    TELEFONO_CLIENTE VARCHAR(50) NULL,
    DIRECCION_CLIENTE VARCHAR(200) NULL,
    CIUDAD_CLIENTE VARCHAR(100) NULL,
    ESTADO_CLIENTE BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE Proveedores (
    ID_PROVEEDOR INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE_PROVEEDOR VARCHAR(150) NOT NULL,
    RAZON_SOCIAL VARCHAR(150) NULL,
    NIT VARCHAR(50) NULL UNIQUE,
    CORREO_PROVEEDOR VARCHAR(120) NULL UNIQUE,
    TELEFONO_PROVEEDOR VARCHAR(50) NULL,
    DIRECCION_PROVEEDOR VARCHAR(200) NULL,
    CIUDAD_PROVEEDOR VARCHAR(100) NULL,
    ESTADO_PROVEEDOR BOOLEAN NOT NULL DEFAULT TRUE
);

-- ============================================
-- 3. TABLAS DEPENDIENTES
-- ============================================

CREATE TABLE Usuarios_Roles (
    ID_USUARIO_ROL INT AUTO_INCREMENT PRIMARY KEY,
    USUARIO_ID INT NOT NULL,
    ROL_ID INT NOT NULL,
    FOREIGN KEY (USUARIO_ID) REFERENCES Usuarios(ID_USUARIO),
    FOREIGN KEY (ROL_ID) REFERENCES Roles(ID_ROLES),
    UNIQUE (USUARIO_ID, ROL_ID)
);

CREATE TABLE Roles_Permisos (
    ID_ROL_PERMISO INT AUTO_INCREMENT PRIMARY KEY,
    ROL_ID INT NOT NULL,
    PERMISOS_ID INT NOT NULL,
    FOREIGN KEY (ROL_ID) REFERENCES Roles(ID_ROLES),
    FOREIGN KEY (PERMISOS_ID) REFERENCES Permisos(ID_PERMISOS),
    UNIQUE (ROL_ID, PERMISOS_ID)
);

CREATE TABLE Correos_Usuarios (
    ID_CORREO INT AUTO_INCREMENT PRIMARY KEY,
    CORREO_USUARIO VARCHAR(120) NOT NULL UNIQUE,
    ES_PRINCIPAL BOOLEAN NULL DEFAULT NULL,
    USUARIO_ID INT NOT NULL,
    FOREIGN KEY (USUARIO_ID) REFERENCES Usuarios(ID_USUARIO),
    UNIQUE (USUARIO_ID, ES_PRINCIPAL)
);

CREATE TABLE Telefonos_Usuarios (
    ID_TELEFONO INT AUTO_INCREMENT PRIMARY KEY,
    TELEFONO_USUARIO VARCHAR(50) NOT NULL,
    ES_PRINCIPAL BOOLEAN NULL DEFAULT NULL,
    USUARIO_ID INT NOT NULL,
    FOREIGN KEY (USUARIO_ID) REFERENCES Usuarios(ID_USUARIO),
    UNIQUE (USUARIO_ID, ES_PRINCIPAL)
);

-- ============================================
-- 4. TABLAS DE PRODUCTOS, VENTAS Y MOVIMIENTOS
-- ============================================

CREATE TABLE Productos (
    ID_PRODUCTO INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE_PRODUCTO VARCHAR(150) NOT NULL,
    DESCRIPCION_PRODUCTO VARCHAR(255),
    PRECIO_VENTA DECIMAL(10,2) NOT NULL,
    COSTO_PROMEDIO DECIMAL(10,2) NOT NULL DEFAULT 0,
    STOCK INT NOT NULL DEFAULT 0,
    ESTADO_PRODUCTO BOOLEAN NOT NULL DEFAULT TRUE,
    CATEGORIA_ID INT NOT NULL,
    FOREIGN KEY (CATEGORIA_ID) REFERENCES Categorias(ID_CATEGORIA)
);

CREATE TABLE Imagenes_Productos (
    IMAGEN_PRODUCTO INT AUTO_INCREMENT PRIMARY KEY,
    URL VARCHAR(255) NOT NULL,
    FECHA_REGISTRO DATE NOT NULL,
    PRODUCTO_ID INT NOT NULL,
    FOREIGN KEY (PRODUCTO_ID) REFERENCES Productos(ID_PRODUCTO)
);

CREATE TABLE Ventas (
    ID_VENTA INT AUTO_INCREMENT PRIMARY KEY,
    FECHA_VENTA DATE NOT NULL,
    TOTAL_VENTA DECIMAL(10,2) NOT NULL,
    METODO_PAGO_VENTA ENUM('Transferencia','Efectivo') NOT NULL,
    USUARIO_ID INT NOT NULL,
    CLIENTE_ID INT NOT NULL,
    FOREIGN KEY (USUARIO_ID) REFERENCES Usuarios(ID_USUARIO),
    FOREIGN KEY (CLIENTE_ID) REFERENCES Clientes(ID_CLIENTE)
);

CREATE TABLE Compras (
    ID_COMPRA INT AUTO_INCREMENT PRIMARY KEY,
    FECHA_COMPRA DATE NOT NULL,
    TOTAL_COMPRA DECIMAL(10,2) NOT NULL,
    METODO_PAGO_COMPRA ENUM('Transferencia','Efectivo') NOT NULL,
    USUARIO_ID INT NOT NULL,
    PROVEEDOR_ID INT NOT NULL,
    FOREIGN KEY (USUARIO_ID) REFERENCES Usuarios(ID_USUARIO),
    FOREIGN KEY (PROVEEDOR_ID) REFERENCES Proveedores(ID_PROVEEDOR)
);

CREATE TABLE Detalles_Compras (
    ID_DET_COMPRA INT AUTO_INCREMENT PRIMARY KEY,
    CANTIDAD_COMPRA INT NOT NULL,
    COSTO_UNITARIO DECIMAL(10,2) NOT NULL,
    SUBTOTAL_COMPRA DECIMAL(10,2) NOT NULL,
    COMPRA_ID INT NOT NULL,
    PRODUCTO_ID INT NOT NULL,
    FOREIGN KEY (COMPRA_ID) REFERENCES Compras(ID_COMPRA),
    FOREIGN KEY (PRODUCTO_ID) REFERENCES Productos(ID_PRODUCTO)
);

CREATE TABLE Detalles_Ventas (
    ID_DET_VENTA INT AUTO_INCREMENT PRIMARY KEY,
    CANTIDAD_VENTA INT NOT NULL,
    PRECIO_UNITARIO DECIMAL(10,2) NOT NULL,
    SUBTOTAL_VENTA DECIMAL(10,2) NOT NULL,
    VENTA_ID INT NOT NULL,
    PRODUCTO_ID INT NOT NULL,
    FOREIGN KEY (VENTA_ID) REFERENCES Ventas(ID_VENTA),
    FOREIGN KEY (PRODUCTO_ID) REFERENCES Productos(ID_PRODUCTO)
);

CREATE TABLE Gastos_Adicionales (
    ID_GASTOS_ADIC INT AUTO_INCREMENT PRIMARY KEY,
    MONTO DECIMAL(10,2) NOT NULL,
    DESCRIPCION_GASTO VARCHAR(255),
    FECHA_REGISTRO DATE NOT NULL,
    METODO_PAGO_GASTO ENUM('Transferencia', 'Efectivo') NOT NULL,
    USUARIO_ID INT NOT NULL,
    FOREIGN KEY (USUARIO_ID) REFERENCES Usuarios(ID_USUARIO)
);

CREATE TABLE Movimientos_Financieros (
    ID_MOVS_FINANCIEROS INT AUTO_INCREMENT PRIMARY KEY,
    CONCEPTO VARCHAR(200) NOT NULL,
    MONTO DECIMAL(10,2) NOT NULL,
    FECHA DATE NOT NULL,
    TIPO_MOVIMIENTO_ID INT NOT NULL,
    VENTA_ID INT NULL,
    COMPRA_ID INT NULL,
    GASTO_ADICIONAL_ID INT NULL,
    FOREIGN KEY (TIPO_MOVIMIENTO_ID) REFERENCES Tipos_Movimientos(ID_TIPO_MOVIMIENTOS),
    FOREIGN KEY (VENTA_ID) REFERENCES Ventas(ID_VENTA),
    FOREIGN KEY (COMPRA_ID) REFERENCES Compras(ID_COMPRA),
    FOREIGN KEY (GASTO_ADICIONAL_ID) REFERENCES Gastos_Adicionales(ID_GASTOS_ADIC)
);

-- ============================================
-- 5. RECUPERACION DE CONTRASENA
-- ============================================

CREATE TABLE Tokens_Recuperacion (
    ID_TOKEN INT AUTO_INCREMENT PRIMARY KEY,
    USUARIO_ID INT NOT NULL,
    TOKEN VARCHAR(255) NOT NULL UNIQUE,
    FECHA_EXPIRACION DATETIME NOT NULL,
    USADO BOOLEAN DEFAULT FALSE,
    FECHA_CREACION DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (USUARIO_ID) REFERENCES Usuarios(ID_USUARIO)
);
