-- ============================================
-- 1. CREAR BASE DE DATOS
-- ============================================
CREATE DATABASE IF NOT EXISTS UrbanLife; 
USE UrbanLife;

-- ============================================
-- 2. TABLAS INDEPENDIENTES
-- ============================================

CREATE TABLE Usuarios (
    ID_USUARIO INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    CORREO VARCHAR(120) NOT NULL UNIQUE,
    CONTRASENA VARCHAR(255) NOT NULL,
    ESTADO BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE Roles (
    ID_ROLES INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    DESCRIPCION VARCHAR(255) NOT NULL
);

CREATE TABLE Permisos (
    ID_PERMISOS INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    DESCRIPCION VARCHAR(255) NOT NULL
);

CREATE TABLE Categoria (
    ID_CATEGORIA INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    DESCRIPCION VARCHAR(255),
    ESTADO BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE Tipo_Movimientos (
    ID_TIPO_MOVIMIENTOS INT AUTO_INCREMENT PRIMARY KEY,
    MOVIMIENTO ENUM('Venta', 'Compra', 'Gasto Adicional') NOT NULL,
    NATURALEZA ENUM('Ingreso', 'Egreso') NOT NULL
);

CREATE TABLE Tipo_Gasto (
    ID_TIPO_GASTO INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    DESCRIPCION VARCHAR(255) NULL
);

-- ============================================
-- 3. TABLAS DEPENDIENTES
-- ============================================

CREATE TABLE Usuario_Rol (
    ID_USUARIO_ROL INT AUTO_INCREMENT PRIMARY KEY,
    USUARIO_ID INT NOT NULL,
    ROL_ID INT NOT NULL,
    FOREIGN KEY (USUARIO_ID) REFERENCES Usuarios(ID_USUARIO),
    FOREIGN KEY (ROL_ID) REFERENCES Roles(ID_ROLES)
);

CREATE TABLE Rol_Permisos (
    ID_ROL_PERMISO INT AUTO_INCREMENT PRIMARY KEY,
    ROL_ID INT NOT NULL,
    PERMISOS_ID INT NOT NULL,
    FOREIGN KEY (ROL_ID) REFERENCES Roles(ID_ROLES),
    FOREIGN KEY (PERMISOS_ID) REFERENCES Permisos(ID_PERMISOS)
);

CREATE TABLE Perfil (
    ID_PERFIL INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE_EMPRESA VARCHAR(150) NULL,
    DIRECCION VARCHAR(200) NOT NULL,
    CIUDAD VARCHAR(100) NOT NULL,
    USUARIO_ID INT NOT NULL,
    FOREIGN KEY (USUARIO_ID) REFERENCES Usuarios(ID_USUARIO)
);

CREATE TABLE Correos_Perfil (
    ID_CORREOS INT AUTO_INCREMENT PRIMARY KEY,
    CORREO VARCHAR(120) NOT NULL,
    PERFIL_ID INT NOT NULL,
    FOREIGN KEY (PERFIL_ID) REFERENCES Perfil(ID_PERFIL)
);

CREATE TABLE Numeros_Perfil (
    ID_NUMEROS INT AUTO_INCREMENT PRIMARY KEY,
    NUMERO VARCHAR(50) NOT NULL,
    PERFIL_ID INT NOT NULL,
    FOREIGN KEY (PERFIL_ID) REFERENCES Perfil(ID_PERFIL)
);

-- ============================================
-- 4. TABLAS DE PRODUCTOS, VENTAS Y MOVIMIENTOS
-- ============================================

CREATE TABLE Producto (
    ID_PRODUCTO INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(150) NOT NULL,
    DESCRIPCION VARCHAR(255),
    PRECIO_VENTA DECIMAL(10,2) NOT NULL,
    COSTO_PROMEDIO DECIMAL(10,2) NOT NULL,
    STOCK INT NOT NULL DEFAULT 0,
    ESTADO BOOLEAN NOT NULL DEFAULT TRUE,
    CATEGORIA_ID INT NOT NULL,
    FOREIGN KEY (CATEGORIA_ID) REFERENCES Categoria(ID_CATEGORIA)
);

CREATE TABLE Imagenes_Producto (
    IMAGEN_PRODUCTO INT AUTO_INCREMENT PRIMARY KEY,
    URL VARCHAR(255) NOT NULL,
    FECHA_REGISTRO DATE NOT NULL,
    PRODUCTO_ID INT NOT NULL,
    FOREIGN KEY (PRODUCTO_ID) REFERENCES Producto(ID_PRODUCTO)
);

CREATE TABLE Venta (
    ID_VENTA INT AUTO_INCREMENT PRIMARY KEY,
    FECHA_VENTA DATE NOT NULL,
    TOTAL_VENTA DECIMAL(10,2) NOT NULL,
    METODO_PAGO ENUM('Transferencia','Efectivo') NOT NULL,
    USUARIO_ID INT NOT NULL,
    FOREIGN KEY (USUARIO_ID) REFERENCES Usuarios(ID_USUARIO)
);

CREATE TABLE Compra (
    ID_COMPRA INT AUTO_INCREMENT PRIMARY KEY,
    FECHA_COMPRA DATE NOT NULL,
    TOTAL_COMPRA DECIMAL(10,2) NOT NULL,
    METODO_PAGO ENUM('Transferencia','Efectivo') NOT NULL,
    USUARIO_ID INT NOT NULL,
    FOREIGN KEY (USUARIO_ID) REFERENCES Usuarios(ID_USUARIO)
);

CREATE TABLE Detalle_Compra (
    ID_DET_COMPRA INT AUTO_INCREMENT PRIMARY KEY,
    CANTIDAD INT NOT NULL,
    COSTO_UNITARIO DECIMAL(10,2) NOT NULL,
    SUBTOTAL DECIMAL(10,2) NOT NULL,
    COMPRA_ID INT NOT NULL,
    PRODUCTO_ID INT NOT NULL,
    FOREIGN KEY (COMPRA_ID) REFERENCES Compra(ID_COMPRA),
    FOREIGN KEY (PRODUCTO_ID) REFERENCES Producto(ID_PRODUCTO)
);

CREATE TABLE Detalle_Venta (
    ID_DET_VENTA INT AUTO_INCREMENT PRIMARY KEY,
    CANTIDAD INT NOT NULL,
    PRECIO_UNITARIO DECIMAL(10,2) NOT NULL,
    SUBTOTAL DECIMAL(10,2) NOT NULL,
    VENTA_ID INT NOT NULL,
    PRODUCTO_ID INT NOT NULL,
    FOREIGN KEY (VENTA_ID) REFERENCES Venta(ID_VENTA),
    FOREIGN KEY (PRODUCTO_ID) REFERENCES Producto(ID_PRODUCTO)
);

CREATE TABLE Movimientos_Financieros (
    ID_MOVS_FINANCIEROS INT AUTO_INCREMENT PRIMARY KEY,
    FECHA_MOVIMIENTO DATE NOT NULL,
    CONCEPTO VARCHAR(200) NOT NULL,
    MONTO DECIMAL(10,2) NOT NULL,
    METODO_PAGO ENUM('Transferencia', 'Efectivo') NOT NULL,
    TIPO_MOVIMIENTO_ID INT NOT NULL,
    USUARIO_ID INT NOT NULL,
    FOREIGN KEY (TIPO_MOVIMIENTO_ID) REFERENCES Tipo_Movimientos(ID_TIPO_MOVIMIENTOS),
    FOREIGN KEY (USUARIO_ID) REFERENCES Usuarios(ID_USUARIO)
);

CREATE TABLE Gastos_Adicionales (
    ID_GASTOS_ADIC INT AUTO_INCREMENT PRIMARY KEY,
    MONTO DECIMAL(10,2) NOT NULL,
    DESCRIPCION VARCHAR(255),
    FECHA_REGISTRO DATE NOT NULL,
    COMPRA_ID INT NULL,
    TIPO_GASTO_ID INT NOT NULL,
    FOREIGN KEY (COMPRA_ID) REFERENCES Compra(ID_COMPRA),
    FOREIGN KEY (TIPO_GASTO_ID) REFERENCES Tipo_Gasto(ID_TIPO_GASTO)
);
